export interface WordEntry {
	word: string;
	vagueHint: string;
}

export const CATEGORIES: Record<string, WordEntry[]> = {
	Food: [
		{ word: "Pizza", vagueHint: "Dish" },
		{ word: "Sushi", vagueHint: "Dish" },
		{ word: "Burger", vagueHint: "Dish" },
		{ word: "Taco", vagueHint: "Dish" },
		{ word: "Ice Cream", vagueHint: "Dessert" },
		{ word: "Pasta", vagueHint: "Dish" },
		{ word: "Salad", vagueHint: "Dish" },
		{ word: "Steak", vagueHint: "Meat" },
		{ word: "Pancake", vagueHint: "Breakfast" },
		{ word: "Sandwich", vagueHint: "Food" },
		{ word: "Apple", vagueHint: "Fruit" },
		{ word: "Banana", vagueHint: "Fruit" },
		{ word: "Cheese", vagueHint: "Dairy" },
		{ word: "Bread", vagueHint: "Baked" },
		{ word: "Chocolate", vagueHint: "Sweet" },
		{ word: "Croissant", vagueHint: "Pastry" },
		{ word: "Burrito", vagueHint: "Dish" },
		{ word: "Soup", vagueHint: "Liquid" },
		{ word: "Donut", vagueHint: "Dessert" },
		{ word: "Waffle", vagueHint: "Breakfast" },
	],
	Places: [
		{ word: "Beach", vagueHint: "Nature" },
		{ word: "Mountain", vagueHint: "Nature" },
		{ word: "Library", vagueHint: "Building" },
		{ word: "Hospital", vagueHint: "Building" },
		{ word: "School", vagueHint: "Building" },
		{ word: "Restaurant", vagueHint: "Business" },
		{ word: "Cinema", vagueHint: "Entertainment" },
		{ word: "Park", vagueHint: "Outdoors" },
		{ word: "Airport", vagueHint: "Transport" },
		{ word: "Museum", vagueHint: "Attraction" },
		{ word: "Hotel", vagueHint: "Lodging" },
		{ word: "Zoo", vagueHint: "Attraction" },
		{ word: "Gym", vagueHint: "Facility" },
		{ word: "Bank", vagueHint: "Business" },
		{ word: "Supermarket", vagueHint: "Store" },
		{ word: "Casino", vagueHint: "Entertainment" },
		{ word: "Stadium", vagueHint: "Venue" },
		{ word: "Theater", vagueHint: "Venue" },
		{ word: "Farm", vagueHint: "Agriculture" },
		{ word: "Castle", vagueHint: "Building" },
	],
	Animals: [
		{ word: "Dog", vagueHint: "Mammal" },
		{ word: "Cat", vagueHint: "Mammal" },
		{ word: "Elephant", vagueHint: "Mammal" },
		{ word: "Lion", vagueHint: "Mammal" },
		{ word: "Tiger", vagueHint: "Mammal" },
		{ word: "Bear", vagueHint: "Mammal" },
		{ word: "Monkey", vagueHint: "Mammal" },
		{ word: "Penguin", vagueHint: "Bird" },
		{ word: "Dolphin", vagueHint: "Mammal" },
		{ word: "Whale", vagueHint: "Mammal" },
		{ word: "Snake", vagueHint: "Reptile" },
		{ word: "Horse", vagueHint: "Mammal" },
		{ word: "Cow", vagueHint: "Mammal" },
		{ word: "Pig", vagueHint: "Mammal" },
		{ word: "Bird", vagueHint: "Avian" },
		{ word: "Shark", vagueHint: "Fish" },
		{ word: "Frog", vagueHint: "Amphibian" },
		{ word: "Turtle", vagueHint: "Reptile" },
		{ word: "Rabbit", vagueHint: "Mammal" },
		{ word: "Deer", vagueHint: "Mammal" },
	],
	"Everyday Objects": [
		{ word: "Phone", vagueHint: "Device" },
		{ word: "Computer", vagueHint: "Device" },
		{ word: "Television", vagueHint: "Device" },
		{ word: "Chair", vagueHint: "Furniture" },
		{ word: "Table", vagueHint: "Furniture" },
		{ word: "Bed", vagueHint: "Furniture" },
		{ word: "Lamp", vagueHint: "Object" },
		{ word: "Clock", vagueHint: "Device" },
		{ word: "Book", vagueHint: "Item" },
		{ word: "Pen", vagueHint: "Tool" },
		{ word: "Key", vagueHint: "Tool" },
		{ word: "Wallet", vagueHint: "Accessory" },
		{ word: "Shoes", vagueHint: "Clothing" },
		{ word: "Glasses", vagueHint: "Accessory" },
		{ word: "Umbrella", vagueHint: "Object" },
		{ word: "Scissors", vagueHint: "Tool" },
		{ word: "Towel", vagueHint: "Object" },
		{ word: "Brush", vagueHint: "Tool" },
		{ word: "Mirror", vagueHint: "Object" },
		{ word: "Knife", vagueHint: "Tool" },
	],
	Jobs: [
		{ word: "Doctor", vagueHint: "Profession" },
		{ word: "Teacher", vagueHint: "Profession" },
		{ word: "Engineer", vagueHint: "Profession" },
		{ word: "Chef", vagueHint: "Profession" },
		{ word: "Artist", vagueHint: "Profession" },
		{ word: "Musician", vagueHint: "Profession" },
		{ word: "Writer", vagueHint: "Profession" },
		{ word: "Actor", vagueHint: "Profession" },
		{ word: "Lawyer", vagueHint: "Profession" },
		{ word: "Police", vagueHint: "Profession" },
		{ word: "Firefighter", vagueHint: "Profession" },
		{ word: "Pilot", vagueHint: "Profession" },
		{ word: "Scientist", vagueHint: "Profession" },
		{ word: "Nurse", vagueHint: "Profession" },
		{ word: "Farmer", vagueHint: "Profession" },
	],
	Sports: [
		{ word: "Soccer", vagueHint: "Sport" },
		{ word: "Basketball", vagueHint: "Sport" },
		{ word: "Tennis", vagueHint: "Sport" },
		{ word: "Baseball", vagueHint: "Sport" },
		{ word: "Golf", vagueHint: "Sport" },
		{ word: "Swimming", vagueHint: "Sport" },
		{ word: "Running", vagueHint: "Sport" },
		{ word: "Cycling", vagueHint: "Sport" },
		{ word: "Volleyball", vagueHint: "Sport" },
		{ word: "Boxing", vagueHint: "Sport" },
		{ word: "Wrestling", vagueHint: "Sport" },
		{ word: "Skiing", vagueHint: "Sport" },
		{ word: "Surfing", vagueHint: "Sport" },
		{ word: "Gymnastics", vagueHint: "Sport" },
		{ word: "Cricket", vagueHint: "Sport" },
	],
	Games: [
		{ word: "Minecraft", vagueHint: "Video Game" },
		{ word: "Mario", vagueHint: "Video Game" },
		{ word: "Chess", vagueHint: "Board Game" },
		{ word: "Poker", vagueHint: "Card Game" },
		{ word: "Tetris", vagueHint: "Video Game" },
		{ word: "Monopoly", vagueHint: "Board Game" },
		{ word: "Scrabble", vagueHint: "Board Game" },
		{ word: "Zelda", vagueHint: "Video Game" },
		{ word: "Halo", vagueHint: "Video Game" },
		{ word: "Pac-Man", vagueHint: "Video Game" },
		{ word: "Fortnite", vagueHint: "Video Game" },
		{ word: "Roblox", vagueHint: "Video Game" },
		{ word: "Pokemon", vagueHint: "Video Game" },
		{ word: "Checkers", vagueHint: "Board Game" },
		{ word: "UNO", vagueHint: "Card Game" },
	],
	"Movies & TV": [
		{ word: "Comedy", vagueHint: "Genre" },
		{ word: "Horror", vagueHint: "Genre" },
		{ word: "Action", vagueHint: "Genre" },
		{ word: "Romance", vagueHint: "Genre" },
		{ word: "Documentary", vagueHint: "Genre" },
		{ word: "Animation", vagueHint: "Genre" },
		{ word: "Sci-Fi", vagueHint: "Genre" },
		{ word: "Fantasy", vagueHint: "Genre" },
		{ word: "Thriller", vagueHint: "Genre" },
		{ word: "Drama", vagueHint: "Genre" },
		{ word: "Actor", vagueHint: "Profession" },
		{ word: "Director", vagueHint: "Profession" },
		{ word: "Camera", vagueHint: "Device" },
		{ word: "Popcorn", vagueHint: "Snack" },
		{ word: "Ticket", vagueHint: "Pass" },
	],
};
