export interface WordEntry {
	word: string;
	vagueHint: string;
}

export const CATEGORIES: Record<string, WordEntry[]> = {
	Food: [
		{ word: "Pizza", vagueHint: "Dish" },
		{ word: "Sushi", vagueHint: "Dish" },
		{ word: "Burger", vagueHint: "Dish" },
		{ word: "Taco", vagueHint: "Dish" },
		{ word: "Ice Cream", vagueHint: "Dessert" },
		{ word: "Pasta", vagueHint: "Dish" },
		{ word: "Salad", vagueHint: "Dish" },
		{ word: "Steak", vagueHint: "Meat" },
		{ word: "Pancake", vagueHint: "Breakfast" },
		{ word: "Sandwich", vagueHint: "Food" },
		{ word: "Apple", vagueHint: "Fruit" },
		{ word: "Banana", vagueHint: "Fruit" },
		{ word: "Cheese", vagueHint: "Dairy" },
		{ word: "Bread", vagueHint: "Baked" },
		{ word: "Chocolate", vagueHint: "Sweet" },
		{ word: "Croissant", vagueHint: "Pastry" },
		{ word: "Burrito", vagueHint: "Dish" },
		{ word: "Soup", vagueHint: "Liquid" },
		{ word: "Donut", vagueHint: "Dessert" },
		{ word: "Waffle", vagueHint: "Breakfast" },
		{ word: "Bacon", vagueHint: "Meat" },
		{ word: "Curry", vagueHint: "Dish" },
		{ word: "Ramen", vagueHint: "Dish" },
		{ word: "Cookie", vagueHint: "Dessert" },
		{ word: "Muffin", vagueHint: "Pastry" },
	],
	Places: [
		{ word: "Beach", vagueHint: "Nature" },
		{ word: "Mountain", vagueHint: "Nature" },
		{ word: "Library", vagueHint: "Building" },
		{ word: "Hospital", vagueHint: "Building" },
		{ word: "School", vagueHint: "Building" },
		{ word: "Restaurant", vagueHint: "Business" },
		{ word: "Cinema", vagueHint: "Entertainment" },
		{ word: "Park", vagueHint: "Outdoors" },
		{ word: "Airport", vagueHint: "Transport" },
		{ word: "Museum", vagueHint: "Attraction" },
		{ word: "Hotel", vagueHint: "Lodging" },
		{ word: "Zoo", vagueHint: "Attraction" },
		{ word: "Gym", vagueHint: "Facility" },
		{ word: "Bank", vagueHint: "Business" },
		{ word: "Supermarket", vagueHint: "Store" },
		{ word: "Casino", vagueHint: "Entertainment" },
		{ word: "Stadium", vagueHint: "Venue" },
		{ word: "Theater", vagueHint: "Venue" },
		{ word: "Farm", vagueHint: "Agriculture" },
		{ word: "Castle", vagueHint: "Building" },
		{ word: "Desert", vagueHint: "Nature" },
		{ word: "Jungle", vagueHint: "Nature" },
		{ word: "Prison", vagueHint: "Facility" },
		{ word: "Church", vagueHint: "Building" },
		{ word: "Office", vagueHint: "Building" },
	],
	Animals: [
		{ word: "Dog", vagueHint: "Mammal" },
		{ word: "Cat", vagueHint: "Mammal" },
		{ word: "Elephant", vagueHint: "Mammal" },
		{ word: "Lion", vagueHint: "Mammal" },
		{ word: "Tiger", vagueHint: "Mammal" },
		{ word: "Bear", vagueHint: "Mammal" },
		{ word: "Monkey", vagueHint: "Mammal" },
		{ word: "Penguin", vagueHint: "Bird" },
		{ word: "Dolphin", vagueHint: "Mammal" },
		{ word: "Whale", vagueHint: "Mammal" },
		{ word: "Snake", vagueHint: "Reptile" },
		{ word: "Horse", vagueHint: "Mammal" },
		{ word: "Cow", vagueHint: "Mammal" },
		{ word: "Pig", vagueHint: "Mammal" },
		{ word: "Bird", vagueHint: "Avian" },
		{ word: "Shark", vagueHint: "Fish" },
		{ word: "Frog", vagueHint: "Amphibian" },
		{ word: "Turtle", vagueHint: "Reptile" },
		{ word: "Rabbit", vagueHint: "Mammal" },
		{ word: "Deer", vagueHint: "Mammal" },
		{ word: "Giraffe", vagueHint: "Mammal" },
		{ word: "Kangaroo", vagueHint: "Mammal" },
		{ word: "Gorilla", vagueHint: "Mammal" },
		{ word: "Octopus", vagueHint: "Mollusk" },
		{ word: "Owl", vagueHint: "Bird" },
	],
	"Everyday Objects": [
		{ word: "Phone", vagueHint: "Device" },
		{ word: "Computer", vagueHint: "Device" },
		{ word: "Television", vagueHint: "Device" },
		{ word: "Chair", vagueHint: "Furniture" },
		{ word: "Table", vagueHint: "Furniture" },
		{ word: "Bed", vagueHint: "Furniture" },
		{ word: "Lamp", vagueHint: "Object" },
		{ word: "Clock", vagueHint: "Device" },
		{ word: "Book", vagueHint: "Item" },
		{ word: "Pen", vagueHint: "Tool" },
		{ word: "Key", vagueHint: "Tool" },
		{ word: "Wallet", vagueHint: "Accessory" },
		{ word: "Shoes", vagueHint: "Clothing" },
		{ word: "Glasses", vagueHint: "Accessory" },
		{ word: "Umbrella", vagueHint: "Object" },
		{ word: "Scissors", vagueHint: "Tool" },
		{ word: "Towel", vagueHint: "Object" },
		{ word: "Brush", vagueHint: "Tool" },
		{ word: "Mirror", vagueHint: "Object" },
		{ word: "Knife", vagueHint: "Tool" },
		{ word: "Backpack", vagueHint: "Accessory" },
		{ word: "Camera", vagueHint: "Device" },
		{ word: "Bicycle", vagueHint: "Vehicle" },
		{ word: "Guitar", vagueHint: "Instrument" },
		{ word: "Toothbrush", vagueHint: "Tool" },
	],
	Jobs: [
		{ word: "Doctor", vagueHint: "Profession" },
		{ word: "Teacher", vagueHint: "Profession" },
		{ word: "Engineer", vagueHint: "Profession" },
		{ word: "Chef", vagueHint: "Profession" },
		{ word: "Artist", vagueHint: "Profession" },
		{ word: "Musician", vagueHint: "Profession" },
		{ word: "Writer", vagueHint: "Profession" },
		{ word: "Actor", vagueHint: "Profession" },
		{ word: "Lawyer", vagueHint: "Profession" },
		{ word: "Police", vagueHint: "Profession" },
		{ word: "Firefighter", vagueHint: "Profession" },
		{ word: "Pilot", vagueHint: "Profession" },
		{ word: "Scientist", vagueHint: "Profession" },
		{ word: "Nurse", vagueHint: "Profession" },
		{ word: "Farmer", vagueHint: "Profession" },
		{ word: "Plumber", vagueHint: "Profession" },
		{ word: "Mechanic", vagueHint: "Profession" },
		{ word: "Dentist", vagueHint: "Profession" },
		{ word: "Astronaut", vagueHint: "Profession" },
		{ word: "Detective", vagueHint: "Profession" },
	],
	Sports: [
		{ word: "Soccer", vagueHint: "Sport" },
		{ word: "Basketball", vagueHint: "Sport" },
		{ word: "Tennis", vagueHint: "Sport" },
		{ word: "Baseball", vagueHint: "Sport" },
		{ word: "Golf", vagueHint: "Sport" },
		{ word: "Swimming", vagueHint: "Sport" },
		{ word: "Running", vagueHint: "Sport" },
		{ word: "Cycling", vagueHint: "Sport" },
		{ word: "Volleyball", vagueHint: "Sport" },
		{ word: "Boxing", vagueHint: "Sport" },
		{ word: "Wrestling", vagueHint: "Sport" },
		{ word: "Skiing", vagueHint: "Sport" },
		{ word: "Surfing", vagueHint: "Sport" },
		{ word: "Gymnastics", vagueHint: "Sport" },
		{ word: "Cricket", vagueHint: "Sport" },
		{ word: "Archery", vagueHint: "Sport" },
		{ word: "Hockey", vagueHint: "Sport" },
		{ word: "Bowling", vagueHint: "Sport" },
		{ word: "Rugby", vagueHint: "Sport" },
		{ word: "Badminton", vagueHint: "Sport" },
	],
	Vehicles: [
		{ word: "Car", vagueHint: "Transport" },
		{ word: "Bus", vagueHint: "Transport" },
		{ word: "Train", vagueHint: "Transport" },
		{ word: "Airplane", vagueHint: "Transport" },
		{ word: "Bicycle", vagueHint: "Transport" },
		{ word: "Motorcycle", vagueHint: "Transport" },
		{ word: "Helicopter", vagueHint: "Transport" },
		{ word: "Boat", vagueHint: "Transport" },
		{ word: "Ship", vagueHint: "Transport" },
		{ word: "Submarine", vagueHint: "Transport" },
		{ word: "Truck", vagueHint: "Transport" },
		{ word: "Van", vagueHint: "Transport" },
		{ word: "Scooter", vagueHint: "Transport" },
		{ word: "Tractor", vagueHint: "Transport" },
		{ word: "Ambulance", vagueHint: "Transport" },
	],
	Nature: [
		{ word: "Tree", vagueHint: "Plant" },
		{ word: "Flower", vagueHint: "Plant" },
		{ word: "Grass", vagueHint: "Plant" },
		{ word: "River", vagueHint: "Water" },
		{ word: "Lake", vagueHint: "Water" },
		{ word: "Ocean", vagueHint: "Water" },
		{ word: "Cloud", vagueHint: "Weather" },
		{ word: "Rain", vagueHint: "Weather" },
		{ word: "Snow", vagueHint: "Weather" },
		{ word: "Sun", vagueHint: "Space" },
		{ word: "Moon", vagueHint: "Space" },
		{ word: "Star", vagueHint: "Space" },
		{ word: "Fire", vagueHint: "Element" },
		{ word: "Rock", vagueHint: "Earth" },
		{ word: "Sand", vagueHint: "Earth" },
	],
};
