export interface WordEntry {
	word: string;
	vagueHint: string;
}

export const CATEGORIES: Record<string, WordEntry[]> = {
	Household: [
		{ word: "Refrigerator", vagueHint: "Cold" },
		{ word: "Washing Machine", vagueHint: "Laundry" },
		{ word: "Microwave", vagueHint: "Heating" },
		{ word: "Television", vagueHint: "Entertainment" },
		{ word: "Sofa", vagueHint: "Seating" },
		{ word: "Bed", vagueHint: "Sleeping" },
		{ word: "Dining Table", vagueHint: "Eating" },
		{ word: "Bookshelf", vagueHint: "Storage" },
		{ word: "Wardrobe", vagueHint: "Clothing" },
		{ word: "Vacuum Cleaner", vagueHint: "Cleaning" },
		{ word: "Toaster", vagueHint: "Breakfast" },
		{ word: "Blender", vagueHint: "Mixing" },
		{ word: "Coffee Maker", vagueHint: "Brewing" },
		{ word: "Iron", vagueHint: "Pressing" },
		{ word: "Hair Dryer", vagueHint: "Blowing" },
		{ word: "Dishwasher", vagueHint: "Washing" },
		{ word: "Oven", vagueHint: "Baking" },
		{ word: "Rug", vagueHint: "Flooring" },
		{ word: "Lamp", vagueHint: "Lighting" },
		{ word: "Fan", vagueHint: "Cooling" },
		{ word: "Air Conditioner", vagueHint: "Climate" },
		{ word: "Heater", vagueHint: "Warming" },
		{ word: "Nightstand", vagueHint: "Bedside" },
		{ word: "Dresser", vagueHint: "Drawers" },
		{ word: "Mirror", vagueHint: "Reflection" },
		{ word: "Toilet", vagueHint: "Bathroom" },
		{ word: "Bathtub", vagueHint: "Bathing" },
		{ word: "Shower", vagueHint: "Washing" },
		{ word: "Sink", vagueHint: "Basin" },
		{ word: "Towel Rack", vagueHint: "Hanging" },
		{ word: "Curtains", vagueHint: "Windows" },
		{ word: "Blinds", vagueHint: "Shading" },
		{ word: "Clock", vagueHint: "Timekeeping" },
		{ word: "Plant Pot", vagueHint: "Container" },
		{ word: "Vase", vagueHint: "Decoration" },
		{ word: "Picture Frame", vagueHint: "Display" },
		{ word: "Trash Can", vagueHint: "Disposal" },
		{ word: "Broom", vagueHint: "Sweeping" },
		{ word: "Mop", vagueHint: "Mopping" },
		{ word: "Dustpan", vagueHint: "Collecting" },
		{ word: "Ironing Board", vagueHint: "Surface" },
		{ word: "Coat Rack", vagueHint: "Hanging" },
		{ word: "Shoe Rack", vagueHint: "Footwear" },
		{ word: "Pantry", vagueHint: "Groceries" },
		{ word: "Fireplace", vagueHint: "Hearth" },
		{ word: "Thermostat", vagueHint: "Temperature" },
		{ word: "Speaker", vagueHint: "Audio" },
		{ word: "Router", vagueHint: "Network" },
		{ word: "Sewing Machine", vagueHint: "Stitching" },
		{ word: "Humidifier", vagueHint: "Moisture" },
	],
	Food: [
		{ word: "Pizza", vagueHint: "Slice" },
		{ word: "Sushi", vagueHint: "Roll" },
		{ word: "Burger", vagueHint: "Patty" },
		{ word: "Taco", vagueHint: "Shell" },
		{ word: "Ice Cream", vagueHint: "Scoop" },
		{ word: "Pasta", vagueHint: "Noodles" },
		{ word: "Salad", vagueHint: "Greens" },
		{ word: "Steak", vagueHint: "Beef" },
		{ word: "Pancake", vagueHint: "Batter" },
		{ word: "Sandwich", vagueHint: "Slices" },
		{ word: "Apple", vagueHint: "Fruit" },
		{ word: "Banana", vagueHint: "Peel" },
		{ word: "Cheese", vagueHint: "Dairy" },
		{ word: "Bread", vagueHint: "Loaf" },
		{ word: "Chocolate", vagueHint: "Cocoa" },
		{ word: "Croissant", vagueHint: "Pastry" },
		{ word: "Burrito", vagueHint: "Wrap" },
		{ word: "Soup", vagueHint: "Broth" },
		{ word: "Donut", vagueHint: "Fried" },
		{ word: "Waffle", vagueHint: "Grid" },
		{ word: "Bacon", vagueHint: "Pork" },
		{ word: "Curry", vagueHint: "Spice" },
		{ word: "Ramen", vagueHint: "Bowl" },
		{ word: "Cookie", vagueHint: "Baked" },
		{ word: "Muffin", vagueHint: "Cup" },
		{ word: "Hot Dog", vagueHint: "Sausage" },
		{ word: "Omelet", vagueHint: "Eggs" },
		{ word: "Cereal", vagueHint: "Breakfast" },
		{ word: "Yogurt", vagueHint: "Cultured" },
		{ word: "French Fries", vagueHint: "Potato" },
		{ word: "Rice", vagueHint: "Grain" },
		{ word: "Fried Chicken", vagueHint: "Poultry" },
		{ word: "Tofu", vagueHint: "Soy" },
		{ word: "Dumplings", vagueHint: "Dough" },
		{ word: "Cheesecake", vagueHint: "Dessert" },
		{ word: "Brownie", vagueHint: "Square" },
		{ word: "Pie", vagueHint: "Crust" },
		{ word: "Stew", vagueHint: "Simmered" },
		{ word: "Chili", vagueHint: "Beans" },
		{ word: "Kebab", vagueHint: "Skewer" },
		{ word: "Meatballs", vagueHint: "Ground" },
		{ word: "Lasagna", vagueHint: "Layers" },
		{ word: "Nachos", vagueHint: "Chips" },
		{ word: "Quesadilla", vagueHint: "Melted" },
		{ word: "Sushi Roll", vagueHint: "Seaweed" },
		{ word: "Cupcake", vagueHint: "Frosted" },
		{ word: "Pretzel", vagueHint: "Twisted" },
		{ word: "Bagel", vagueHint: "Ring" },
		{ word: "Croquette", vagueHint: "Crumbed" },
		{ word: "Pudding", vagueHint: "Creamy" },
	],
	Places: [
		{ word: "Eiffel Tower", vagueHint: "Landmark" },
		{ word: "Statue of Liberty", vagueHint: "Monument" },
		{ word: "Great Wall of China", vagueHint: "Fortification" },
		{ word: "Pyramids of Giza", vagueHint: "Tombs" },
		{ word: "Colosseum", vagueHint: "Amphitheater" },
		{ word: "Taj Mahal", vagueHint: "Mausoleum" },
		{ word: "Machu Picchu", vagueHint: "Ruins" },
		{ word: "Mount Everest", vagueHint: "Peak" },
		{ word: "Grand Canyon", vagueHint: "Gorge" },
		{ word: "Niagara Falls", vagueHint: "Cascade" },
		{ word: "Sahara Desert", vagueHint: "Dunes" },
		{ word: "Amazon Rainforest", vagueHint: "Jungle" },
		{ word: "Stonehenge", vagueHint: "Megaliths" },
		{ word: "Sydney Opera House", vagueHint: "Venue" },
		{ word: "Louvre", vagueHint: "Gallery" },
		{ word: "Beach", vagueHint: "Coast" },
		{ word: "Mountain", vagueHint: "Altitude" },
		{ word: "Library", vagueHint: "Books" },
		{ word: "Hospital", vagueHint: "Medical" },
		{ word: "School", vagueHint: "Education" },
		{ word: "Restaurant", vagueHint: "Dining" },
		{ word: "Cinema", vagueHint: "Movies" },
		{ word: "Park", vagueHint: "Recreation" },
		{ word: "Airport", vagueHint: "Aviation" },
		{ word: "Museum", vagueHint: "Exhibits" },
		{ word: "Hotel", vagueHint: "Lodging" },
		{ word: "Zoo", vagueHint: "Enclosures" },
		{ word: "Gym", vagueHint: "Fitness" },
		{ word: "Bank", vagueHint: "Finance" },
		{ word: "Supermarket", vagueHint: "Groceries" },
		{ word: "Casino", vagueHint: "Gambling" },
		{ word: "Stadium", vagueHint: "Sports" },
		{ word: "Theater", vagueHint: "Stage" },
		{ word: "Farm", vagueHint: "Agriculture" },
		{ word: "Castle", vagueHint: "Fortress" },
		{ word: "Desert", vagueHint: "Arid" },
		{ word: "Jungle", vagueHint: "Tropical" },
		{ word: "Prison", vagueHint: "Incarceration" },
		{ word: "Church", vagueHint: "Worship" },
		{ word: "Office", vagueHint: "Workplace" },
		{ word: "Police Station", vagueHint: "Law" },
		{ word: "Fire Station", vagueHint: "Emergency" },
		{ word: "Post Office", vagueHint: "Mail" },
		{ word: "Bakery", vagueHint: "Ovens" },
		{ word: "Pharmacy", vagueHint: "Medication" },
		{ word: "Mall", vagueHint: "Shopping" },
		{ word: "Arcade", vagueHint: "Gaming" },
		{ word: "Theme Park", vagueHint: "Rides" },
		{ word: "Aquarium", vagueHint: "Marine" },
		{ word: "Bar", vagueHint: "Drinks" },
	],
	Animals: [
		{ word: "Elephant", vagueHint: "Trunk" },
		{ word: "Giraffe", vagueHint: "Neck" },
		{ word: "Penguin", vagueHint: "Flightless" },
		{ word: "Dolphin", vagueHint: "Aquatic" },
		{ word: "Kangaroo", vagueHint: "Pouch" },
		{ word: "Tiger", vagueHint: "Stripes" },
		{ word: "Cheetah", vagueHint: "Speed" },
		{ word: "Rhinoceros", vagueHint: "Horn" },
		{ word: "Zebra", vagueHint: "Pattern" },
		{ word: "Gorilla", vagueHint: "Primate" },
		{ word: "Hippopotamus", vagueHint: "River" },
		{ word: "Crocodile", vagueHint: "Reptile" },
		{ word: "Ostrich", vagueHint: "Bird" },
		{ word: "Sloth", vagueHint: "Slow" },
		{ word: "Koala", vagueHint: "Marsupial" },
		{ word: "Platypus", vagueHint: "Monotreme" },
		{ word: "Octopus", vagueHint: "Tentacles" },
		{ word: "Jellyfish", vagueHint: "Sting" },
		{ word: "Seahorse", vagueHint: "Ocean" },
		{ word: "Starfish", vagueHint: "Echinoderm" },
		{ word: "Dog", vagueHint: "Canine" },
		{ word: "Cat", vagueHint: "Feline" },
		{ word: "Lion", vagueHint: "Mane" },
		{ word: "Bear", vagueHint: "Hibernation" },
		{ word: "Monkey", vagueHint: "Tail" },
		{ word: "Whale", vagueHint: "Blowhole" },
		{ word: "Snake", vagueHint: "Slither" },
		{ word: "Horse", vagueHint: "Hooves" },
		{ word: "Cow", vagueHint: "Bovine" },
		{ word: "Pig", vagueHint: "Snout" },
		{ word: "Shark", vagueHint: "Fins" },
		{ word: "Frog", vagueHint: "Amphibian" },
		{ word: "Turtle", vagueHint: "Shell" },
		{ word: "Rabbit", vagueHint: "Ears" },
		{ word: "Deer", vagueHint: "Antlers" },
		{ word: "Owl", vagueHint: "Nocturnal" },
		{ word: "Fox", vagueHint: "Cunning" },
		{ word: "Wolf", vagueHint: "Howl" },
		{ word: "Eagle", vagueHint: "Predator" },
		{ word: "Hawk", vagueHint: "Talons" },
		{ word: "Mouse", vagueHint: "Rodent" },
		{ word: "Rat", vagueHint: "Scavenger" },
		{ word: "Squirrel", vagueHint: "Acorns" },
		{ word: "Raccoon", vagueHint: "Bandit" },
		{ word: "Bat", vagueHint: "Sonar" },
		{ word: "Camel", vagueHint: "Hump" },
		{ word: "Llama", vagueHint: "Fleece" },
		{ word: "Sheep", vagueHint: "Wool" },
		{ word: "Goat", vagueHint: "Horns" },
		{ word: "Chicken", vagueHint: "Feathers" },
	],
	"Everyday Objects": [
		{ word: "Phone", vagueHint: "Communication" },
		{ word: "Laptop", vagueHint: "Computing" },
		{ word: "Chair", vagueHint: "Sitting" },
		{ word: "Table", vagueHint: "Surface" },
		{ word: "Lamp", vagueHint: "Illumination" },
		{ word: "Clock", vagueHint: "Time" },
		{ word: "Book", vagueHint: "Reading" },
		{ word: "Pen", vagueHint: "Writing" },
		{ word: "Key", vagueHint: "Locking" },
		{ word: "Wallet", vagueHint: "Money" },
		{ word: "Shoes", vagueHint: "Walking" },
		{ word: "Glasses", vagueHint: "Vision" },
		{ word: "Umbrella", vagueHint: "Rain" },
		{ word: "Scissors", vagueHint: "Cutting" },
		{ word: "Towel", vagueHint: "Drying" },
		{ word: "Brush", vagueHint: "Grooming" },
		{ word: "Mirror", vagueHint: "Looking" },
		{ word: "Knife", vagueHint: "Slicing" },
		{ word: "Backpack", vagueHint: "Carrying" },
		{ word: "Camera", vagueHint: "Photography" },
		{ word: "Toothbrush", vagueHint: "Dental" },
		{ word: "Watch", vagueHint: "Wrist" },
		{ word: "Comb", vagueHint: "Hair" },
		{ word: "Tissue", vagueHint: "Wiping" },
		{ word: "Notebook", vagueHint: "Notes" },
		{ word: "Pencil", vagueHint: "Graphite" },
		{ word: "Eraser", vagueHint: "Mistakes" },
		{ word: "Mug", vagueHint: "Drinking" },
		{ word: "Fork", vagueHint: "Utensil" },
		{ word: "Spoon", vagueHint: "Scooping" },
		{ word: "Plate", vagueHint: "Serving" },
		{ word: "Bowl", vagueHint: "Vessel" },
		{ word: "Remote", vagueHint: "Control" },
		{ word: "Charger", vagueHint: "Power" },
		{ word: "Headphones", vagueHint: "Listening" },
		{ word: "Sunglasses", vagueHint: "Shade" },
		{ word: "Lighter", vagueHint: "Flame" },
		{ word: "Flashlight", vagueHint: "Beam" },
		{ word: "Tape", vagueHint: "Adhesive" },
		{ word: "Stapler", vagueHint: "Binding" },
		{ word: "Paperclip", vagueHint: "Attaching" },
		{ word: "Rubber Band", vagueHint: "Elastic" },
		{ word: "Bottle", vagueHint: "Liquid" },
		{ word: "Can", vagueHint: "Tin" },
		{ word: "Matches", vagueHint: "Igniting" },
		{ word: "Envelope", vagueHint: "Mailing" },
		{ word: "Deodorant", vagueHint: "Hygiene" },
		{ word: "Soap", vagueHint: "Lather" },
		{ word: "Shampoo", vagueHint: "Washing" },
		{ word: "Toilet Paper", vagueHint: "Paper" },
	],
	Jobs: [
		{ word: "Doctor", vagueHint: "Health" },
		{ word: "Teacher", vagueHint: "Education" },
		{ word: "Engineer", vagueHint: "Design" },
		{ word: "Chef", vagueHint: "Cooking" },
		{ word: "Artist", vagueHint: "Creation" },
		{ word: "Musician", vagueHint: "Performance" },
		{ word: "Writer", vagueHint: "Literature" },
		{ word: "Actor", vagueHint: "Theater" },
		{ word: "Lawyer", vagueHint: "Legal" },
		{ word: "Police Officer", vagueHint: "Law" },
		{ word: "Firefighter", vagueHint: "Rescue" },
		{ word: "Pilot", vagueHint: "Aviation" },
		{ word: "Scientist", vagueHint: "Research" },
		{ word: "Nurse", vagueHint: "Care" },
		{ word: "Farmer", vagueHint: "Agriculture" },
		{ word: "Plumber", vagueHint: "Pipes" },
		{ word: "Mechanic", vagueHint: "Repair" },
		{ word: "Dentist", vagueHint: "Teeth" },
		{ word: "Astronaut", vagueHint: "Space" },
		{ word: "Detective", vagueHint: "Investigation" },
		{ word: "Architect", vagueHint: "Buildings" },
		{ word: "Photographer", vagueHint: "Pictures" },
		{ word: "Journalist", vagueHint: "News" },
		{ word: "Baker", vagueHint: "Oven" },
		{ word: "Butcher", vagueHint: "Meat" },
		{ word: "Carpenter", vagueHint: "Wood" },
		{ word: "Electrician", vagueHint: "Wiring" },
		{ word: "Barber", vagueHint: "Hair" },
		{ word: "Tailor", vagueHint: "Clothing" },
		{ word: "Veterinarian", vagueHint: "Animals" },
		{ word: "Surgeon", vagueHint: "Operation" },
		{ word: "Pharmacist", vagueHint: "Medicine" },
		{ word: "Librarian", vagueHint: "Books" },
		{ word: "Accountant", vagueHint: "Finance" },
		{ word: "Banker", vagueHint: "Money" },
		{ word: "Real Estate Agent", vagueHint: "Property" },
		{ word: "Politician", vagueHint: "Government" },
		{ word: "Judge", vagueHint: "Court" },
		{ word: "Security Guard", vagueHint: "Protection" },
		{ word: "Waiter", vagueHint: "Service" },
		{ word: "Bartender", vagueHint: "Drinks" },
		{ word: "Janitor", vagueHint: "Cleaning" },
		{ word: "Driver", vagueHint: "Transport" },
		{ word: "Programmer", vagueHint: "Code" },
		{ word: "Graphic Designer", vagueHint: "Visuals" },
		{ word: "Consultant", vagueHint: "Advice" },
		{ word: "CEO", vagueHint: "Executive" },
		{ word: "Manager", vagueHint: "Leadership" },
		{ word: "Therapist", vagueHint: "Counseling" },
		{ word: "Soldier", vagueHint: "Military" },
	],
	Sports: [
		{ word: "Soccer", vagueHint: "Goal" },
		{ word: "Basketball", vagueHint: "Hoop" },
		{ word: "Tennis", vagueHint: "Racket" },
		{ word: "Baseball", vagueHint: "Bat" },
		{ word: "Golf", vagueHint: "Clubs" },
		{ word: "Swimming", vagueHint: "Pool" },
		{ word: "Running", vagueHint: "Track" },
		{ word: "Cycling", vagueHint: "Bike" },
		{ word: "Volleyball", vagueHint: "Net" },
		{ word: "Boxing", vagueHint: "Ring" },
		{ word: "Wrestling", vagueHint: "Mat" },
		{ word: "Skiing", vagueHint: "Snow" },
		{ word: "Surfing", vagueHint: "Waves" },
		{ word: "Gymnastics", vagueHint: "Vault" },
		{ word: "Cricket", vagueHint: "Wicket" },
		{ word: "Archery", vagueHint: "Bow" },
		{ word: "Hockey", vagueHint: "Puck" },
		{ word: "Bowling", vagueHint: "Pins" },
		{ word: "Rugby", vagueHint: "Scrum" },
		{ word: "Badminton", vagueHint: "Shuttlecock" },
		{ word: "Table Tennis", vagueHint: "Paddle" },
		{ word: "Fencing", vagueHint: "Sword" },
		{ word: "Judo", vagueHint: "Throw" },
		{ word: "Karate", vagueHint: "Strike" },
		{ word: "Taekwondo", vagueHint: "Kick" },
		{ word: "Snowboarding", vagueHint: "Board" },
		{ word: "Skateboarding", vagueHint: "Ramp" },
		{ word: "Rock Climbing", vagueHint: "Wall" },
		{ word: "Rowing", vagueHint: "Oars" },
		{ word: "Sailing", vagueHint: "Boat" },
		{ word: "Diving", vagueHint: "Board" },
		{ word: "Water Polo", vagueHint: "Water" },
		{ word: "Handball", vagueHint: "Court" },
		{ word: "Softball", vagueHint: "Pitch" },
		{ word: "Lacrosse", vagueHint: "Stick" },
		{ word: "Marathon", vagueHint: "Distance" },
		{ word: "Triathlon", vagueHint: "Endurance" },
		{ word: "Weightlifting", vagueHint: "Barbell" },
		{ word: "Powerlifting", vagueHint: "Strength" },
		{ word: "Figure Skating", vagueHint: "Ice" },
		{ word: "Curling", vagueHint: "Stone" },
		{ word: "Bobsleigh", vagueHint: "Sled" },
		{ word: "Luge", vagueHint: "Slide" },
		{ word: "Skeleton", vagueHint: "Headfirst" },
		{ word: "Equestrian", vagueHint: "Horse" },
		{ word: "Polo", vagueHint: "Mallet" },
		{ word: "Squash", vagueHint: "Wall" },
		{ word: "Racquetball", vagueHint: "Bounce" },
		{ word: "Billiards", vagueHint: "Cue" },
		{ word: "Darts", vagueHint: "Board" },
	],
	Vehicles: [
		{ word: "Car", vagueHint: "Automobile" },
		{ word: "Bus", vagueHint: "Transit" },
		{ word: "Train", vagueHint: "Railway" },
		{ word: "Airplane", vagueHint: "Flight" },
		{ word: "Bicycle", vagueHint: "Pedaling" },
		{ word: "Motorcycle", vagueHint: "Riding" },
		{ word: "Helicopter", vagueHint: "Rotor" },
		{ word: "Boat", vagueHint: "Watercraft" },
		{ word: "Ship", vagueHint: "Vessel" },
		{ word: "Submarine", vagueHint: "Underwater" },
		{ word: "Truck", vagueHint: "Hauling" },
		{ word: "Van", vagueHint: "Cargo" },
		{ word: "Scooter", vagueHint: "Motorized" },
		{ word: "Tractor", vagueHint: "Farming" },
		{ word: "Ambulance", vagueHint: "Emergency" },
		{ word: "Fire Engine", vagueHint: "Rescue" },
		{ word: "Police Car", vagueHint: "Patrol" },
		{ word: "Taxi", vagueHint: "Cab" },
		{ word: "Limousine", vagueHint: "Luxury" },
		{ word: "SUV", vagueHint: "Spacious" },
		{ word: "Minivan", vagueHint: "Family" },
		{ word: "RV", vagueHint: "Motorhome" },
		{ word: "Camper", vagueHint: "Travel" },
		{ word: "Jet Ski", vagueHint: "Watercraft" },
		{ word: "Snowmobile", vagueHint: "Winter" },
		{ word: "Hovercraft", vagueHint: "Gliding" },
		{ word: "Blimp", vagueHint: "Airship" },
		{ word: "Hot Air Balloon", vagueHint: "Floating" },
		{ word: "Glider", vagueHint: "Soaring" },
		{ word: "Space Shuttle", vagueHint: "Orbit" },
		{ word: "Rocket", vagueHint: "Launch" },
		{ word: "Ferry", vagueHint: "Crossing" },
		{ word: "Yacht", vagueHint: "Luxury" },
		{ word: "Sailboat", vagueHint: "Wind" },
		{ word: "Canoe", vagueHint: "Paddling" },
		{ word: "Kayak", vagueHint: "Rowing" },
		{ word: "Raft", vagueHint: "Floating" },
		{ word: "Gondola", vagueHint: "Canal" },
		{ word: "Tram", vagueHint: "Streetcar" },
		{ word: "Trolley", vagueHint: "Cable" },
		{ word: "Subway", vagueHint: "Underground" },
		{ word: "Monorail", vagueHint: "Elevated" },
		{ word: "Bulldozer", vagueHint: "Earthmoving" },
		{ word: "Excavator", vagueHint: "Digging" },
		{ word: "Crane", vagueHint: "Lifting" },
		{ word: "Forklift", vagueHint: "Warehouse" },
		{ word: "Go-Kart", vagueHint: "Racing" },
		{ word: "Segway", vagueHint: "Balancing" },
		{ word: "Skateboard", vagueHint: "Rolling" },
		{ word: "Wheelchair", vagueHint: "Mobility" },
	],
	Nature: [
		{ word: "Tree", vagueHint: "Flora" },
		{ word: "Flower", vagueHint: "Blossom" },
		{ word: "Grass", vagueHint: "Lawn" },
		{ word: "River", vagueHint: "Flow" },
		{ word: "Lake", vagueHint: "Waterbody" },
		{ word: "Ocean", vagueHint: "Sea" },
		{ word: "Cloud", vagueHint: "Sky" },
		{ word: "Rain", vagueHint: "Precipitation" },
		{ word: "Snow", vagueHint: "Winter" },
		{ word: "Sun", vagueHint: "Star" },
		{ word: "Moon", vagueHint: "Satellite" },
		{ word: "Star", vagueHint: "Celestial" },
		{ word: "Fire", vagueHint: "Flame" },
		{ word: "Rock", vagueHint: "Stone" },
		{ word: "Sand", vagueHint: "Beach" },
		{ word: "Dirt", vagueHint: "Soil" },
		{ word: "Mud", vagueHint: "Wet" },
		{ word: "Leaf", vagueHint: "Foliage" },
		{ word: "Branch", vagueHint: "Limb" },
		{ word: "Root", vagueHint: "Underground" },
		{ word: "Bark", vagueHint: "Trunk" },
		{ word: "Bush", vagueHint: "Shrub" },
		{ word: "Vine", vagueHint: "Climber" },
		{ word: "Moss", vagueHint: "Carpet" },
		{ word: "Fern", vagueHint: "Frond" },
		{ word: "Mushroom", vagueHint: "Fungus" },
		{ word: "Hill", vagueHint: "Mound" },
		{ word: "Valley", vagueHint: "Depression" },
		{ word: "Cave", vagueHint: "Cavern" },
		{ word: "Volcano", vagueHint: "Eruption" },
		{ word: "Island", vagueHint: "Landmass" },
		{ word: "Peninsula", vagueHint: "Cape" },
		{ word: "Gulf", vagueHint: "Inlet" },
		{ word: "Bay", vagueHint: "Cove" },
		{ word: "Stream", vagueHint: "Brook" },
		{ word: "Creek", vagueHint: "Rivulet" },
		{ word: "Waterfall", vagueHint: "Cascade" },
		{ word: "Glacier", vagueHint: "Ice" },
		{ word: "Iceberg", vagueHint: "Floe" },
		{ word: "Wind", vagueHint: "Breeze" },
		{ word: "Storm", vagueHint: "Tempest" },
		{ word: "Lightning", vagueHint: "Bolt" },
		{ word: "Thunder", vagueHint: "Boom" },
		{ word: "Fog", vagueHint: "Mist" },
		{ word: "Mist", vagueHint: "Haze" },
		{ word: "Tornado", vagueHint: "Twister" },
		{ word: "Hurricane", vagueHint: "Cyclone" },
		{ word: "Earthquake", vagueHint: "Tremor" },
		{ word: "Rainbow", vagueHint: "Spectrum" },
		{ word: "Meteor", vagueHint: "Shooting" },
	],
};
